import { ImageResponse } from "next/og";

// Dynamic Open Graph image generated by next/og at build time. Picked up
// automatically by Next.js metadata for OG + Twitter cards when this file
// sits at app/opengraph-image.tsx — no manual metadata.openGraph.images entry
// needed. Renders edge-fast and stays in lockstep with brand tokens because
// it's defined here, not in a static PNG checked into /public.
export const runtime = "edge";
export const alt = "beuwy — Brand · Site · Agent-Layer in 10 Tagen";
export const size = { width: 1200, height: 630 };
export const contentType = "image/png";

export default async function OpengraphImage() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          padding: "72px 80px",
          // Bordeaux base + warm radial stage light (matches globals.css
          // --bg-base + --glow-yellow + the ambient-blob stage lamp).
          backgroundColor: "#1A0404",
          backgroundImage:
            "radial-gradient(ellipse 70% 55% at 60% 35%, rgba(247,233,154,0.18), transparent 70%), radial-gradient(ellipse 50% 40% at 30% 80%, rgba(255,95,95,0.10), transparent 70%)",
          color: "#FFFDF3",
          fontFamily: "serif",
        }}
      >
        {/* Eyebrow row */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 14,
            color: "#C2B89F",
            fontFamily: "ui-monospace, monospace",
            fontSize: 18,
            letterSpacing: "0.14em",
            textTransform: "uppercase",
          }}
        >
          <span
            style={{
              display: "flex",
              width: 36,
              height: 1,
              backgroundColor: "#F7E99A",
            }}
          />
          <span>beuwy.com · Operator-Studio · seit 2017</span>
        </div>

        {/* Headline */}
        <div style={{ display: "flex", flexDirection: "column", gap: 32 }}>
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              fontSize: 92,
              lineHeight: 0.98,
              letterSpacing: "-0.028em",
              color: "#F7E99A",
              fontStyle: "normal",
              fontWeight: 400,
              maxWidth: 1040,
            }}
          >
            <span>Die Marke,</span>
            <span style={{ display: "flex", gap: 18 }}>
              <span>die ein</span>
              <span style={{ fontStyle: "italic" }}>Agent</span>
            </span>
            <span>zuerst empfiehlt.</span>
          </div>

          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: 20,
              fontFamily: "sans-serif",
              fontSize: 24,
              color: "#FFFDF3",
              opacity: 0.78,
              letterSpacing: "-0.01em",
            }}
          >
            <span>Brand · Site · Agent-Layer</span>
            <span style={{ color: "#F7E99A" }}>·</span>
            <span>10 Tage</span>
            <span style={{ color: "#F7E99A" }}>·</span>
            <span>Festpreis</span>
          </div>
        </div>

        {/* Footer rail */}
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "flex-end",
            color: "#8A8068",
            fontFamily: "ui-monospace, monospace",
            fontSize: 18,
            letterSpacing: "0.08em",
            textTransform: "uppercase",
          }}
        >
          <span style={{ display: "flex", gap: 16 }}>
            <span>Heidelberg</span>
            <span style={{ color: "#3A0808" }}>·</span>
            <span>Mannheim</span>
            <span style={{ color: "#3A0808" }}>·</span>
            <span>Berlin</span>
          </span>
          <span style={{ color: "#F7E99A", fontStyle: "italic", fontFamily: "serif", fontSize: 28, letterSpacing: "-0.02em" }}>
            beuwy
          </span>
        </div>
      </div>
    ),
    { ...size },
  );
}
