/** R11-Abnahme: Studio (Unterseiten-Bereich mit Seitenwahl, Frontseite-Bereich) + /intern/einstellungen. Server mit STUDIO_PASSWORD=studio-test-1234. */
import { chromium } from "playwright-core";
import fs from "node:fs";
const ausgabe = "docs/redesign/refs/review";
const basis = process.env.BASIS || "http://localhost:3100";
fs.mkdirSync(ausgabe, { recursive: true });
const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const login = await ctx.request.post(`${basis}/api/studio/login`, { data: { password: process.env.STUDIO_PW || "studio-test-1234" } });
console.log("login", login.status());
const pg = await ctx.newPage();
await pg.route("**beuwy-2.b-cdn.net/**", (r) => r.abort());
await pg.goto(`${basis}/studio`, { waitUntil: "networkidle", timeout: 90000 });
await pg.waitForTimeout(800);
await pg.screenshot({ path: `${ausgabe}/r11-studio-start.png` });
await pg.getByRole("button", { name: /Unterseiten/ }).first().click();
await pg.waitForTimeout(600);
await pg.screenshot({ path: `${ausgabe}/r11-studio-unterseiten.png` });
const select = pg.locator("#studio-seite");
await select.selectOption({ index: 5 });
await pg.waitForTimeout(500);
await pg.screenshot({ path: `${ausgabe}/r11-studio-seite.png` });
await pg.getByRole("button", { name: /Frontseite/ }).first().click();
await pg.waitForTimeout(500);
await pg.screenshot({ path: `${ausgabe}/r11-studio-vsl.png` });
await pg.goto(`${basis}/intern/einstellungen`, { waitUntil: "networkidle", timeout: 90000 });
await pg.waitForTimeout(500);
await pg.screenshot({ path: `${ausgabe}/r11-einstellungen.png` });
console.log("ok");
await browser.close();
