/* GENERIERT von tools/texte-index.mjs — nicht von Hand ändern. */
import * as S_ai_overviews_immobilien from "./ai-overviews-immobilien";
import * as S_alleinauftrag_gewinnen from "./alleinauftrag-gewinnen";
import * as S_anfrage from "./anfrage";
import * as S_automatisierung_maklerbuero from "./automatisierung-maklerbuero";
import * as S_barrierefreie_maklerwebsite from "./barrierefreie-maklerwebsite";
import * as S_beste_maklerwebsites from "./beste-maklerwebsites";
import * as S_bewertungen_aufbauen from "./bewertungen-aufbauen";
import * as S_bottimmo_alternative from "./bottimmo-alternative";
import * as S_bottimmo_erfahrungen from "./bottimmo-erfahrungen";
import * as S_casaone_website from "./casaone-website";
import * as S_cases_detail from "./cases-detail";
import * as S_cases from "./cases";
import * as S_chatgpt_fuer_makler from "./chatgpt-fuer-makler";
import * as S_check from "./check";
import * as S_eigentuemer_leads_generieren from "./eigentuemer-leads-generieren";
import * as S_email_marketing_immobilienmakler from "./email-marketing-immobilienmakler";
import * as S_empfehlungsgeschaeft_digitalisieren from "./empfehlungsgeschaeft-digitalisieren";
import * as S_exposes_die_verkaufen from "./exposes-die-verkaufen";
import * as S_flowfact_website from "./flowfact-website";
import * as S_geo_checkliste from "./geo-checkliste";
import * as S_geo_fuer_immobilienmakler from "./geo-fuer-immobilienmakler";
import * as S_google_unternehmensprofil_makler from "./google-unternehmensprofil-makler";
import * as S_immobilien_farming from "./immobilien-farming";
import * as S_immobilienfotografie_briefing from "./immobilienfotografie-briefing";
import * as S_immobilienmakler_werbung from "./immobilienmakler-werbung";
import * as S_immobilienmarketing_agentur from "./immobilienmarketing-agentur";
import * as S_immobilienmarketing from "./immobilienmarketing";
import * as S_immoscout_profil_vs_eigene_website from "./immoscout-profil-vs-eigene-website";
import * as S_ki_expose_texte from "./ki-expose-texte";
import * as S_ki_fuer_immobilienmakler from "./ki-fuer-immobilienmakler";
import * as S_ki_immobilienbewertung from "./ki-immobilienbewertung";
import * as S_ki_richtlinien_maklerbuero from "./ki-richtlinien-maklerbuero";
import * as S_landingpage_immobilienbewertung from "./landingpage-immobilienbewertung";
import * as S_lead_anbieter_vergleich from "./lead-anbieter-vergleich";
import * as S_leadgenerierung_immobilienmakler from "./leadgenerierung-immobilienmakler";
import * as S_luxusimmobilien_vermarkten from "./luxusimmobilien-vermarkten";
import * as S_makler_crm_einfuehren from "./makler-crm-einfuehren";
import * as S_makler_in_kleinstadt from "./makler-in-kleinstadt";
import * as S_makler_kennzahlen from "./makler-kennzahlen";
import * as S_makler_newsletter_beispiele from "./makler-newsletter-beispiele";
import * as S_makler_positionierung from "./makler-positionierung";
import * as S_makler_website_baukasten_vergleich from "./makler-website-baukasten-vergleich";
import * as S_makler_website_fehler from "./makler-website-fehler";
import * as S_maklerbuero_skalieren from "./maklerbuero-skalieren";
import * as S_maklersoftware_vergleich from "./maklersoftware-vergleich";
import * as S_maklerwebsite_kosten from "./maklerwebsite-kosten";
import * as S_markenaufbau_makler from "./markenaufbau-makler";
import * as S_marketing_bautraeger from "./marketing-bautraeger";
import * as S_marketing_immobilienvertrieb from "./marketing-immobilienvertrieb";
import * as S_marketing_kapitalanlage_immobilien from "./marketing-kapitalanlage-immobilien";
import * as S_marketing_projektentwickler from "./marketing-projektentwickler";
import * as S_mcmakler_modell from "./mcmakler-modell";
import * as S_objektakquise_strategien from "./objektakquise-strategien";
import * as S_onboarding_neuer_mandate from "./onboarding-neuer-mandate";
import * as S_onoffice_website from "./onoffice-website";
import * as S_openimmo_schnittstelle from "./openimmo-schnittstelle";
import * as S_performance_marketing_makler from "./performance-marketing-makler";
import * as S_perplexity_immobiliensuche from "./perplexity-immobiliensuche";
import * as S_propstack_website from "./propstack-website";
import * as S_provision_verteidigen from "./provision-verteidigen";
import * as S_seo_fuer_immobilienmakler from "./seo-fuer-immobilienmakler";
import * as S_social_media_immobilienmakler from "./social-media-immobilienmakler";
import * as S_termin from "./termin";
import * as S_tools_afa_rechner from "./tools-afa-rechner";
import * as S_tools_mietpreisrechner from "./tools-mietpreisrechner";
import * as S_tools_verkaufspreisrechner from "./tools-verkaufspreisrechner";
import * as S_tools from "./tools";
import * as S_ueber_uns from "./ueber-uns";
import * as S_verkaeufer_ansprechen from "./verkaeufer-ansprechen";
import * as S_video_analyse from "./video-analyse";
import * as S_video_fuer_makler from "./video-fuer-makler";
import * as S_website_fuer_immobilienmakler from "./website-fuer-immobilienmakler";
import * as S_website_relaunch_makler from "./website-relaunch-makler";
import * as S_wissen_afa_immobilien from "./wissen-afa-immobilien";
import * as S_wissen_immobilie_bewerten from "./wissen-immobilie-bewerten";
import * as S_wissen_mietpreis_ermitteln from "./wissen-mietpreis-ermitteln";
import * as S_wissen_restnutzungsdauer_gutachten from "./wissen-restnutzungsdauer-gutachten";
import * as S_wissen_spekulationssteuer_immobilien from "./wissen-spekulationssteuer-immobilien";
import * as S_wissen_verkehrswert_vs_marktpreis from "./wissen-verkehrswert-vs-marktpreis";
import * as S_wissen from "./wissen";

type Seite = { SEITE: { slug: string; titel: string; route: string }; DEFAULTS: Record<string, string>; LABELS: Record<string, string> };
const SEITEN: Seite[] = [S_ai_overviews_immobilien, S_alleinauftrag_gewinnen, S_anfrage, S_automatisierung_maklerbuero, S_barrierefreie_maklerwebsite, S_beste_maklerwebsites, S_bewertungen_aufbauen, S_bottimmo_alternative, S_bottimmo_erfahrungen, S_casaone_website, S_cases_detail, S_cases, S_chatgpt_fuer_makler, S_check, S_eigentuemer_leads_generieren, S_email_marketing_immobilienmakler, S_empfehlungsgeschaeft_digitalisieren, S_exposes_die_verkaufen, S_flowfact_website, S_geo_checkliste, S_geo_fuer_immobilienmakler, S_google_unternehmensprofil_makler, S_immobilien_farming, S_immobilienfotografie_briefing, S_immobilienmakler_werbung, S_immobilienmarketing_agentur, S_immobilienmarketing, S_immoscout_profil_vs_eigene_website, S_ki_expose_texte, S_ki_fuer_immobilienmakler, S_ki_immobilienbewertung, S_ki_richtlinien_maklerbuero, S_landingpage_immobilienbewertung, S_lead_anbieter_vergleich, S_leadgenerierung_immobilienmakler, S_luxusimmobilien_vermarkten, S_makler_crm_einfuehren, S_makler_in_kleinstadt, S_makler_kennzahlen, S_makler_newsletter_beispiele, S_makler_positionierung, S_makler_website_baukasten_vergleich, S_makler_website_fehler, S_maklerbuero_skalieren, S_maklersoftware_vergleich, S_maklerwebsite_kosten, S_markenaufbau_makler, S_marketing_bautraeger, S_marketing_immobilienvertrieb, S_marketing_kapitalanlage_immobilien, S_marketing_projektentwickler, S_mcmakler_modell, S_objektakquise_strategien, S_onboarding_neuer_mandate, S_onoffice_website, S_openimmo_schnittstelle, S_performance_marketing_makler, S_perplexity_immobiliensuche, S_propstack_website, S_provision_verteidigen, S_seo_fuer_immobilienmakler, S_social_media_immobilienmakler, S_termin, S_tools_afa_rechner, S_tools_mietpreisrechner, S_tools_verkaufspreisrechner, S_tools, S_ueber_uns, S_verkaeufer_ansprechen, S_video_analyse, S_video_fuer_makler, S_website_fuer_immobilienmakler, S_website_relaunch_makler, S_wissen_afa_immobilien, S_wissen_immobilie_bewerten, S_wissen_mietpreis_ermitteln, S_wissen_restnutzungsdauer_gutachten, S_wissen_spekulationssteuer_immobilien, S_wissen_verkehrswert_vs_marktpreis, S_wissen];

export const SEITEN_MANIFEST: Array<{ slug: string; titel: string; route: string }> = SEITEN.map((s) => s.SEITE);
export const SEITEN_DEFAULTS: Record<string, string> = Object.assign({}, ...SEITEN.map((s) => s.DEFAULTS));
export const SEITEN_LABELS: Record<string, string> = Object.assign({}, ...SEITEN.map((s) => s.LABELS));
